name: dogbreeds_api
description: A Dart API client for the DogAPI
version: 1.0.0+1
publish_to: none

environment:
   sdk: ">=2.19.0 <3.0.0"

dependencies: 
   equatable: ^2.0.5
   http: ^1.1.0
   json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.6.0
