name: favourites_api
description: A Dart API client for adding favourites to Firestore
version: 1.0.0+1
publish_to: none

environment:
   sdk: ">=2.19.0 <3.0.0"

dependencies:
  dogbreeds_api:
    path: ../dogbreeds_api
  firebase_auth: ^4.2.6
  cloud_firestore: ^4.4.0

dev_dependencies: